services:
  nginx:
    image: nginx:1.27-alpine
    platform: linux/amd64
    cpus: 0.10
    mem_limit: 24m
    init: true
    restart: on-failure
    ports:
      - '9999:9999'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

  api1:
    image: gustavotinoo/rinha-fraud-api:v0.3.0-89ccd13
    platform: linux/amd64
    cpus: 0.45
    mem_limit: 163m
    init: true
    restart: on-failure
    environment:
      NODE_ENV: production
      PORT: 8080
      BODY_LIMIT_BYTES: 1048576
    expose:
      - '8080'
    healthcheck:
      test: ['CMD', 'wget', '-qO-', '--tries=1', 'http://localhost:9999/ready']
      interval: 2s
      timeout: 1s
      retries: 30
      start_period: 5s
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

  api2:
    image: gustavotinoo/rinha-fraud-api:v0.3.0-89ccd13
    platform: linux/amd64
    cpus: 0.45
    mem_limit: 163m
    init: true
    restart: on-failure
    environment:
      NODE_ENV: production
      PORT: 8080
      BODY_LIMIT_BYTES: 1048576
    expose:
      - '8080'
    healthcheck:
      test: ['CMD', 'wget', '-qO-', '--tries=1', 'http://localhost:9999/ready']
      interval: 2s
      timeout: 1s
      retries: 30
      start_period: 5s
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'
